import {
  Zap,
  Battery,
  Box,
  Cog,
  Circle,
  Hexagon,
  Square,
  Package,
  Bolt,
  Gauge,
  Cpu,
  Cable,
  Wind,
  Droplet,
} from "lucide-react"
import type { LinkType, Category } from "./types"

export const COMPONENT_CATEGORIES: Record<string, Category> = {
  mechanical: {
    name: "Mechanical",
    icon: Cog,
    components: [
      { id: "frame", name: "Frame", icon: Box, customColor: "#dbeafe" },
      { id: "gear", name: "Gear", icon: Cog, customColor: "#f3e8ff" },
      { id: "bearing", name: "Bearing", icon: Circle, customColor: "#e0e7ff" },
      { id: "shaft", name: "Shaft", icon: Bolt, customColor: "#c7d2fe" },
      { id: "wheel", name: "Wheel", icon: Circle, customColor: "#ddd6fe" },
      { id: "spring", name: "Spring", icon: Wind, customColor: "#e9d5ff" },
      { id: "bracket", name: "Bracket", icon: Square, customColor: "#f3e8ff" },
      { id: "housing", name: "Housing", icon: Package, customColor: "#dbeafe" },
    ],
  },
  electrical: {
    name: "Electrical",
    icon: Zap,
    components: [
      { id: "motor", name: "Motor", icon: Zap, customColor: "#fef3c7" },
      { id: "battery", name: "Battery", icon: Battery, customColor: "#d1fae5" },
      { id: "transformer", name: "Transformer", icon: Zap, customColor: "#fef9c3" },
      { id: "capacitor", name: "Capacitor", icon: Battery, customColor: "#d9f99d" },
      { id: "resistor", name: "Resistor", icon: Cable, customColor: "#fde68a" },
      { id: "relay", name: "Relay", icon: Zap, customColor: "#fed7aa" },
      { id: "fuse", name: "Fuse", icon: Zap, customColor: "#fecaca" },
      { id: "wire", name: "Wire/Cable", icon: Cable, customColor: "#e0e7ff" },
    ],
  },
  control: {
    name: "Control & Sensors",
    icon: Hexagon,
    components: [
      { id: "controller", name: "Controller", icon: Hexagon, customColor: "#fce7f3" },
      { id: "sensor", name: "Sensor", icon: Circle, customColor: "#fee2e2" },
      { id: "plc", name: "PLC", icon: Cpu, customColor: "#fbcfe8" },
      { id: "encoder", name: "Encoder", icon: Gauge, customColor: "#fce7f3" },
      { id: "pressure", name: "Pressure Sensor", icon: Gauge, customColor: "#fecdd3" },
      { id: "temperature", name: "Temperature Sensor", icon: Gauge, customColor: "#fed7aa" },
      { id: "proximity", name: "Proximity Sensor", icon: Circle, customColor: "#fbbf24" },
      { id: "switch", name: "Switch", icon: Square, customColor: "#e0e7ff" },
    ],
  },
  hydraulic: {
    name: "Hydraulic & Pneumatic",
    icon: Droplet,
    components: [
      { id: "pump", name: "Pump", icon: Droplet, customColor: "#cffafe" },
      { id: "cylinder", name: "Cylinder", icon: Package, customColor: "#a5f3fc" },
      { id: "valve", name: "Valve", icon: Droplet, customColor: "#67e8f9" },
      { id: "hose", name: "Hose", icon: Cable, customColor: "#bae6fd" },
      { id: "filter", name: "Filter", icon: Box, customColor: "#7dd3fc" },
      { id: "accumulator", name: "Accumulator", icon: Battery, customColor: "#93c5fd" },
    ],
  },
}

export const ALL_COMPONENTS = Object.values(COMPONENT_CATEGORIES).flatMap((cat) => cat.components)

export const LINK_TYPES: LinkType[] = [
  {
    id: "assembly",
    name: "Assembly",
    color: "#3b82f6",
    strokeWidth: 2,
    dashArray: "",
    description: "Parts assembled together",
  },
  {
    id: "power",
    name: "Power",
    color: "#eab308",
    strokeWidth: 3,
    dashArray: "",
    description: "Electrical power connection",
  },
  { id: "data", name: "Data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5", description: "Data/signal flow" },
  { id: "material", name: "Material", color: "#10b981", strokeWidth: 2, dashArray: "", description: "Material flow" },
  {
    id: "dependency",
    name: "Dependency",
    color: "#ef4444",
    strokeWidth: 2,
    dashArray: "10,5",
    description: "Depends on",
  },
  {
    id: "sequence",
    name: "Sequence",
    color: "#06b6d4",
    strokeWidth: 2,
    dashArray: "",
    description: "Sequential order",
  },
]

export const SAMPLE_DATA = {
  parts: [
    // Chassis & Structure (Center)
    {
      id: 1,
      type: "frame",
      name: "Robot Chassis",
      customColor: "#dbeafe",
      functionality: "Aluminum 6061-T6 chassis with integrated mounting points for all subsystems. Dimensions: 400x300x80mm",
      imageUrl: "",
      cost: "185",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "https://example.com/chassis",
      x: 600,
      y: 400,
    },
    
    // Locomotion System (Bottom area)
    {
      id: 2,
      type: "motor",
      name: "Drive Motor Left",
      customColor: "#fef3c7",
      functionality: "12V DC geared motor, 100 RPM, 5kg-cm torque with integrated encoder (360 PPR)",
      imageUrl: "",
      cost: "45",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 200,
      y: 700,
    },
    {
      id: 3,
      type: "motor",
      name: "Drive Motor Right",
      customColor: "#fef3c7",
      functionality: "12V DC geared motor, 100 RPM, 5kg-cm torque with integrated encoder (360 PPR)",
      imageUrl: "",
      cost: "45",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 1000,
      y: 700,
    },
    {
      id: 4,
      type: "wheel",
      name: "Omni Wheels",
      customColor: "#ddd6fe",
      functionality: "4-inch diameter omni-directional wheels with rubber rollers for smooth movement",
      imageUrl: "",
      cost: "28",
      costUnit: "USD",
      quantity: 4,
      sourceUrl: "",
      x: 600,
      y: 850,
    },
    
    // Power System (Top area)
    {
      id: 5,
      type: "battery",
      name: "LiPo Battery Pack",
      customColor: "#d1fae5",
      functionality: "14.8V 5000mAh 4S LiPo battery with protection circuit, ~2 hour runtime",
      imageUrl: "",
      cost: "89",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 600,
      y: 50,
    },
    {
      id: 6,
      type: "transformer",
      name: "Power Distribution Board",
      customColor: "#fef9c3",
      functionality: "Voltage regulation: 5V/3A, 12V/5A rails with overcurrent protection and status LEDs",
      imageUrl: "",
      cost: "35",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 400,
      y: 200,
    },
    
    // Control System (Center-left)
    {
      id: 7,
      type: "controller",
      name: "Main Controller",
      customColor: "#fce7f3",
      functionality: "Raspberry Pi 4B 4GB - Main processing unit running ROS2 for navigation and control",
      imageUrl: "",
      cost: "75",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 300,
      y: 400,
    },
    {
      id: 8,
      type: "plc",
      name: "Motor Driver Board",
      customColor: "#fbcfe8",
      functionality: "Dual H-bridge motor driver, 12V 5A per channel with current sensing and thermal protection",
      imageUrl: "",
      cost: "25",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 300,
      y: 600,
    },
    
    // Sensing System (Right side)
    {
      id: 9,
      type: "sensor",
      name: "LiDAR Scanner",
      customColor: "#fee2e2",
      functionality: "360° 2D LiDAR, 12m range, 5Hz scan rate for SLAM navigation and obstacle avoidance",
      imageUrl: "",
      cost: "299",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 900,
      y: 250,
    },
    {
      id: 10,
      type: "sensor",
      name: "RGB-D Camera",
      customColor: "#fee2e2",
      functionality: "Intel RealSense D435i with IMU, 1280x720@30fps RGB + depth for object recognition",
      imageUrl: "",
      cost: "199",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 900,
      y: 450,
    },
    {
      id: 11,
      type: "encoder",
      name: "IMU Sensor",
      customColor: "#fce7f3",
      functionality: "9-DOF IMU (gyro, accel, magnetometer) for orientation and motion tracking",
      imageUrl: "",
      cost: "15",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 1100,
      y: 300,
    },
    {
      id: 12,
      type: "proximity",
      name: "Ultrasonic Sensors",
      customColor: "#fbbf24",
      functionality: "HC-SR04 ultrasonic sensors, 2-400cm range for close-range obstacle detection",
      imageUrl: "",
      cost: "8",
      costUnit: "USD",
      quantity: 6,
      sourceUrl: "",
      x: 1100,
      y: 500,
    },
    
    // Manipulation System (Left side)
    {
      id: 13,
      type: "motor",
      name: "Servo Motor",
      customColor: "#fef3c7",
      functionality: "High-torque servo motor 20kg-cm for robotic arm base rotation",
      imageUrl: "",
      cost: "32",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 50,
      y: 300,
    },
    {
      id: 14,
      type: "gear",
      name: "Gripper Assembly",
      customColor: "#f3e8ff",
      functionality: "2-finger parallel gripper with force feedback, 50mm max opening",
      imageUrl: "",
      cost: "65",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 50,
      y: 500,
    },
    
    // Communication & Interface (Top-right)
    {
      id: 15,
      type: "wire",
      name: "Wireless Module",
      customColor: "#e0e7ff",
      functionality: "WiFi 6 + Bluetooth 5.0 module for remote control and telemetry",
      imageUrl: "",
      cost: "22",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 800,
      y: 100,
    },
    {
      id: 16,
      type: "switch",
      name: "Emergency Stop",
      customColor: "#e0e7ff",
      functionality: "Large red emergency stop button with wireless kill switch capability",
      imageUrl: "",
      cost: "18",
      costUnit: "USD",
      quantity: 1,
      sourceUrl: "",
      x: 800,
      y: 50,
    },
  ],
  connections: [
    // Chassis Assembly Connections
    { from: 1, to: 2, id: 101, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    { from: 1, to: 3, id: 102, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    { from: 1, to: 7, id: 103, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    { from: 1, to: 9, id: 104, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    { from: 1, to: 10, id: 105, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    { from: 1, to: 13, id: 106, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    
    // Power Distribution
    { from: 5, to: 6, id: 201, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    { from: 6, to: 7, id: 202, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    { from: 6, to: 8, id: 203, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    { from: 6, to: 9, id: 204, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    { from: 6, to: 10, id: 205, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    { from: 6, to: 15, id: 206, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    
    // Motor Control
    { from: 8, to: 2, id: 301, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    { from: 8, to: 3, id: 302, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    { from: 8, to: 13, id: 303, linkType: "power", color: "#eab308", strokeWidth: 3, dashArray: "" },
    
    // Data/Control Connections
    { from: 7, to: 8, id: 401, linkType: "data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5" },
    { from: 7, to: 9, id: 402, linkType: "data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5" },
    { from: 7, to: 10, id: 403, linkType: "data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5" },
    { from: 7, to: 11, id: 404, linkType: "data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5" },
    { from: 7, to: 12, id: 405, linkType: "data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5" },
    { from: 7, to: 15, id: 406, linkType: "data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5" },
    { from: 7, to: 16, id: 407, linkType: "data", color: "#8b5cf6", strokeWidth: 2, dashArray: "5,5" },
    
    // Mechanical Connections
    { from: 2, to: 4, id: 501, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    { from: 3, to: 4, id: 502, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    { from: 13, to: 14, id: 503, linkType: "assembly", color: "#3b82f6", strokeWidth: 2, dashArray: "" },
    
    // Dependency Relationships
    { from: 9, to: 7, id: 601, linkType: "dependency", color: "#ef4444", strokeWidth: 2, dashArray: "10,5" },
    { from: 10, to: 7, id: 602, linkType: "dependency", color: "#ef4444", strokeWidth: 2, dashArray: "10,5" },
    { from: 11, to: 7, id: 603, linkType: "dependency", color: "#ef4444", strokeWidth: 2, dashArray: "10,5" },
  ],
}
